server:
  port: 9003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.242.52:3306/notes?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true& allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.242.52
    port: 6379
  main:
    allow-circular-references: true # 允许循环调用bean
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上传文件路径配置
notes:
  file:
    upload:
      url: /http/nginx/html/static/note/upload